git init
git add "D:\Photos\github uploads\2022 - My Engagement\Couple Photos\01.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Couple Photos\thumbnails\01.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Couple Photos\DSC_0154.JPG"
git add "D:\Photos\github uploads\2022 - My Engagement\Couple Photos\thumbnails\DSC_0154.JPG"
git add "D:\Photos\github uploads\2022 - My Engagement\Couple Photos\DSC_0156.JPG"
git add "D:\Photos\github uploads\2022 - My Engagement\Couple Photos\thumbnails\DSC_0156.JPG"
git add "D:\Photos\github uploads\2022 - My Engagement\Couple Photos\DSC_0158.JPG"
git add "D:\Photos\github uploads\2022 - My Engagement\Couple Photos\thumbnails\DSC_0158.JPG"
git add "D:\Photos\github uploads\2022 - My Engagement\Couple Photos\DSC_0159.JPG"
git add "D:\Photos\github uploads\2022 - My Engagement\Couple Photos\thumbnails\DSC_0159.JPG"
git add "D:\Photos\github uploads\2022 - My Engagement\Couple Photos\DSC_0167.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Couple Photos\thumbnails\DSC_0167.jpg"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-Engagment-offical-photos.git"
git push -u origin main
git add "D:\Photos\github uploads\2022 - My Engagement\Couple Photos\DSC_0170.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Couple Photos\thumbnails\DSC_0170.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Couple Photos\DSC_0171.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Couple Photos\thumbnails\DSC_0171.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Couple Photos\DSC_0210.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Couple Photos\thumbnails\DSC_0210.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Couple Photos\DSC_0217.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Couple Photos\thumbnails\DSC_0217.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Couple Photos\DSC_0222.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Couple Photos\thumbnails\DSC_0222.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Couple Photos\DSC_0233.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Couple Photos\thumbnails\DSC_0233.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Couple Photos\DSC_0236.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Couple Photos\thumbnails\DSC_0236.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Couple Photos\DSC_0238.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Couple Photos\thumbnails\DSC_0238.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Couple Photos\DSC_0239.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Couple Photos\thumbnails\DSC_0239.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Couple Photos\DSC_0241.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Couple Photos\thumbnails\DSC_0241.jpg"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-Engagment-offical-photos.git"
git push -u origin main
git add "D:\Photos\github uploads\2022 - My Engagement\Couple Photos\DSC_0242.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Couple Photos\thumbnails\DSC_0242.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Couple Photos\DSC_0261.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Couple Photos\thumbnails\DSC_0261.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Couple Photos\DSC_0262.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Couple Photos\thumbnails\DSC_0262.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Couple Photos\DSC_0263.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Couple Photos\thumbnails\DSC_0263.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Couple Photos\DSC_0269.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Couple Photos\thumbnails\DSC_0269.jpg"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-Engagment-offical-photos.git"
git push -u origin main
git add "D:\Photos\github uploads\2022 - My Engagement\Couple Photos\DSC_0271.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Couple Photos\thumbnails\DSC_0271.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Couple Photos\DSC_0272.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Couple Photos\thumbnails\DSC_0272.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Couple Photos\DSC_0276.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Couple Photos\thumbnails\DSC_0276.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Couple Photos\DSC_0292.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Couple Photos\thumbnails\DSC_0292.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Couple Photos\DSC_0294.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Couple Photos\thumbnails\DSC_0294.jpg"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-Engagment-offical-photos.git"
git push -u origin main
git add "D:\Photos\github uploads\2022 - My Engagement\Couple Photos\DSC_0297.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Couple Photos\thumbnails\DSC_0297.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Couple Photos\DSC_0298.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Couple Photos\thumbnails\DSC_0298.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Couple Photos\DSC_0299.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Couple Photos\thumbnails\DSC_0299.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Couple Photos\DSC_0300.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Couple Photos\thumbnails\DSC_0300.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Couple Photos\DSC_0304.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Couple Photos\thumbnails\DSC_0304.jpg"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-Engagment-offical-photos.git"
git push -u origin main
git add "D:\Photos\github uploads\2022 - My Engagement\Couple Photos\DSC_0305.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Couple Photos\thumbnails\DSC_0305.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Couple Photos\DSC_0321.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Couple Photos\thumbnails\DSC_0321.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Couple Photos\DSC_0332.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Couple Photos\thumbnails\DSC_0332.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Couple Photos\DSC_0337.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Couple Photos\thumbnails\DSC_0337.jpg"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-Engagment-offical-photos.git"
git push -u origin main
git add "D:\Photos\github uploads\2022 - My Engagement\Couple Photos\DSC_0341.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Couple Photos\thumbnails\DSC_0341.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Couple Photos\DSC_0344.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Couple Photos\thumbnails\DSC_0344.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Couple Photos\DSC_0346.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Couple Photos\thumbnails\DSC_0346.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Couple Photos\DSC_0348.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Couple Photos\thumbnails\DSC_0348.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Couple Photos\DSC_0349.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Couple Photos\thumbnails\DSC_0349.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Couple Photos\DSC_0355.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Couple Photos\thumbnails\DSC_0355.jpg"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-Engagment-offical-photos.git"
git push -u origin main
git add "D:\Photos\github uploads\2022 - My Engagement\Couple Photos\DSC_0658.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Couple Photos\thumbnails\DSC_0658.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0357.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0357.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0361.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0361.jpg"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-Engagment-offical-photos.git"
git push -u origin main
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0362.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0362.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0363.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0363.jpg"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-Engagment-offical-photos.git"
git push -u origin main
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0365.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0365.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0366.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0366.jpg"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-Engagment-offical-photos.git"
git push -u origin main
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0369.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0369.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0372.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0372.jpg"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-Engagment-offical-photos.git"
git push -u origin main
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0374.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0374.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0375.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0375.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0376.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0376.jpg"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-Engagment-offical-photos.git"
git push -u origin main
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0377.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0377.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0379.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0379.jpg"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-Engagment-offical-photos.git"
git push -u origin main
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0380.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0380.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0382.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0382.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0385.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0385.jpg"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-Engagment-offical-photos.git"
git push -u origin main
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0386.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0386.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0387.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0387.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0390.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0390.jpg"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-Engagment-offical-photos.git"
git push -u origin main
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0393.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0393.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0394.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0394.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0395.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0395.jpg"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-Engagment-offical-photos.git"
git push -u origin main
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0396.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0396.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0397.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0397.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0398.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0398.jpg"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-Engagment-offical-photos.git"
git push -u origin main
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0399.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0399.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0400.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0400.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0402.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0402.jpg"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-Engagment-offical-photos.git"
git push -u origin main
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0403.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0403.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0405.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0405.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0407.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0407.jpg"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-Engagment-offical-photos.git"
git push -u origin main
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0408.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0408.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0409.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0409.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0411.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0411.jpg"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-Engagment-offical-photos.git"
git push -u origin main
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0414.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0414.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0416.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0416.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0419.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0419.jpg"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-Engagment-offical-photos.git"
git push -u origin main
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0420.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0420.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0421.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0421.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0424.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0424.jpg"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-Engagment-offical-photos.git"
git push -u origin main
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0425.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0425.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0427.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0427.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0428.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0428.jpg"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-Engagment-offical-photos.git"
git push -u origin main
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0431.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0431.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0434.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0434.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0436.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0436.jpg"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-Engagment-offical-photos.git"
git push -u origin main
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0439.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0439.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0441.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0441.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0442.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0442.jpg"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-Engagment-offical-photos.git"
git push -u origin main
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0443.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0443.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0444.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0444.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0446.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0446.jpg"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-Engagment-offical-photos.git"
git push -u origin main
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0447.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0447.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0450.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0450.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0451.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0451.jpg"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-Engagment-offical-photos.git"
git push -u origin main
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0453.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0453.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0454.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0454.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0455.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0455.jpg"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-Engagment-offical-photos.git"
git push -u origin main
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0456.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0456.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0458.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0458.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0459.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0459.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0460.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0460.jpg"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-Engagment-offical-photos.git"
git push -u origin main
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0461.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0461.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0462.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0462.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0463.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0463.jpg"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-Engagment-offical-photos.git"
git push -u origin main
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0464.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0464.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0465.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0465.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0466.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0466.jpg"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-Engagment-offical-photos.git"
git push -u origin main
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0467.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0467.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0468.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0468.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0469.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0469.jpg"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-Engagment-offical-photos.git"
git push -u origin main
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0470.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0470.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0471.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0471.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0472.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0472.jpg"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-Engagment-offical-photos.git"
git push -u origin main
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0473.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0473.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0474.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0474.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0475.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0475.jpg"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-Engagment-offical-photos.git"
git push -u origin main
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0476.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0476.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0477.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0477.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0478.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0478.jpg"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-Engagment-offical-photos.git"
git push -u origin main
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0479.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0479.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0480.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0480.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0481.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0481.jpg"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-Engagment-offical-photos.git"
git push -u origin main
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0482.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0482.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0483.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0483.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0484.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0484.jpg"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-Engagment-offical-photos.git"
git push -u origin main
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0488.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0488.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0489.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0489.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0491.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0491.jpg"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-Engagment-offical-photos.git"
git push -u origin main
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0492.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0492.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0494.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0494.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0495.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0495.jpg"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-Engagment-offical-photos.git"
git push -u origin main
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0497.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0497.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0499.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0499.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0502.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0502.jpg"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-Engagment-offical-photos.git"
git push -u origin main
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0505.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0505.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0506.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0506.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0508.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0508.jpg"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-Engagment-offical-photos.git"
git push -u origin main
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0509.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0509.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0511.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0511.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0512.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0512.jpg"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-Engagment-offical-photos.git"
git push -u origin main
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0513.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0513.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0514.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0514.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0515.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0515.jpg"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-Engagment-offical-photos.git"
git push -u origin main
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0522.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0522.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0524.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0524.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0526.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0526.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0528.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0528.jpg"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-Engagment-offical-photos.git"
git push -u origin main
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0530.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0530.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0534.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0534.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0536.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0536.jpg"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-Engagment-offical-photos.git"
git push -u origin main
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0539.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0539.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0543.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0543.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0545.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0545.jpg"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-Engagment-offical-photos.git"
git push -u origin main
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0548.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0548.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0550.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0550.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0552.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0552.jpg"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-Engagment-offical-photos.git"
git push -u origin main
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0553.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0553.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0555.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0555.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0556.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0556.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0557.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0557.jpg"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-Engagment-offical-photos.git"
git push -u origin main
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0558.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0558.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0559.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0559.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0560.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0560.jpg"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-Engagment-offical-photos.git"
git push -u origin main
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0561.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0561.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0563.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0563.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0564.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0564.jpg"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-Engagment-offical-photos.git"
git push -u origin main
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0566.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0566.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0567.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0567.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0568.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0568.jpg"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-Engagment-offical-photos.git"
git push -u origin main
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0569.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0569.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0570.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0570.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0573.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0573.jpg"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-Engagment-offical-photos.git"
git push -u origin main
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0574.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0574.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0575.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0575.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0577.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0577.jpg"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-Engagment-offical-photos.git"
git push -u origin main
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0578.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0578.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0580.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0580.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0581.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0581.jpg"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-Engagment-offical-photos.git"
git push -u origin main
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0583.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0583.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0584.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0584.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0585.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0585.jpg"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-Engagment-offical-photos.git"
git push -u origin main
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0586.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0586.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0587.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0587.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0590.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0590.jpg"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-Engagment-offical-photos.git"
git push -u origin main
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0591.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0591.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0592.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0592.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0594.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0594.jpg"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-Engagment-offical-photos.git"
git push -u origin main
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0595.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0595.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0597.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0597.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0598.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0598.jpg"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-Engagment-offical-photos.git"
git push -u origin main
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0599.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0599.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0601.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0601.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0602.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0602.jpg"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-Engagment-offical-photos.git"
git push -u origin main
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0604.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0604.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0605.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0605.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0607.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0607.jpg"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-Engagment-offical-photos.git"
git push -u origin main
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0608.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0608.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0609.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0609.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0613.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0613.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0614.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0614.jpg"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-Engagment-offical-photos.git"
git push -u origin main
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0617.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0617.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0620.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0620.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0624.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0624.jpg"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-Engagment-offical-photos.git"
git push -u origin main
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0628.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0628.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0635.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0635.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0647.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0647.jpg"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-Engagment-offical-photos.git"
git push -u origin main
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0648.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0648.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0650.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0650.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0651.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0651.jpg"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-Engagment-offical-photos.git"
git push -u origin main
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0652.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0652.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0653.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0653.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0654.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0654.jpg"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-Engagment-offical-photos.git"
git push -u origin main
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0657.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0657.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0660.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0660.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0661.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0661.jpg"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-Engagment-offical-photos.git"
git push -u origin main
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0663.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0663.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0664.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0664.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0665.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0665.jpg"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-Engagment-offical-photos.git"
git push -u origin main
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0666.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0666.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0667.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0667.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0668.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0668.jpg"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-Engagment-offical-photos.git"
git push -u origin main
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0669.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0669.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0670.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0670.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0671.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0671.jpg"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-Engagment-offical-photos.git"
git push -u origin main
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0672.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0672.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0673.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0673.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0674.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0674.jpg"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-Engagment-offical-photos.git"
git push -u origin main
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0675.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0675.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0676.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0676.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0677.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0677.jpg"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-Engagment-offical-photos.git"
git push -u origin main
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0678.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0678.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0680.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0680.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0681.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0681.jpg"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-Engagment-offical-photos.git"
git push -u origin main
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0682.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0682.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0683.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0683.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0684.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0684.jpg"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-Engagment-offical-photos.git"
git push -u origin main
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0685.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0685.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0687.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0687.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0688.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0688.jpg"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-Engagment-offical-photos.git"
git push -u origin main
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0689.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0689.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0690.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0690.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0691.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0691.jpg"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-Engagment-offical-photos.git"
git push -u origin main
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0693.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0693.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0694.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0694.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0695.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0695.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0697.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0697.jpg"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-Engagment-offical-photos.git"
git push -u origin main
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0698.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0698.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0700.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0700.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0701.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0701.jpg"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-Engagment-offical-photos.git"
git push -u origin main
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0702.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0702.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0704.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0704.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0705.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0705.jpg"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-Engagment-offical-photos.git"
git push -u origin main
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0706.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0706.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0707.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0707.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0709.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0709.jpg"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-Engagment-offical-photos.git"
git push -u origin main
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0710.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0710.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0711.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0711.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0715.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0715.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0716.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0716.jpg"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-Engagment-offical-photos.git"
git push -u origin main
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0718.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0718.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0719.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0719.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0721.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0721.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0722.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0722.jpg"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-Engagment-offical-photos.git"
git push -u origin main
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0723.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0723.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0724.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0724.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0728.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0728.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0729.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0729.jpg"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-Engagment-offical-photos.git"
git push -u origin main
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0731.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0731.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0732.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0732.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0743.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0743.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0744.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0744.jpg"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-Engagment-offical-photos.git"
git push -u origin main
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0745.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0745.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0746.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0746.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0747.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0747.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0748.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0748.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0749.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0749.jpg"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-Engagment-offical-photos.git"
git push -u origin main
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0751.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0751.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\DSC_0755.jpg"
git add "D:\Photos\github uploads\2022 - My Engagement\Engagement\thumbnails\DSC_0755.jpg"
git commit -m "adding files"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-Engagment-offical-photos.git"
git push -u origin main
git add *
git commit -m "everything else"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-Engagment-offical-photos.git"
git push -u origin main